<?php
// +----------------------------------------------------------------------
// | OneThink [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013 http://www.onethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: 麦当苗儿 <zuojiazi@vip.qq.com> <http://www.zjzit.cn>
// +----------------------------------------------------------------------

namespace Home\Controller;
use Common\Controller\BaseController;
use Think\Log;
/**
 * 前台公共控制器
 * 为防止多分组Controller名称冲突，公共Controller名称统一使用分组名称
 */
class SearchController extends BaseController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $tree = D('ProposalType')->where(array('status' => 1))->select();
        $this->assign('tree',$tree);
        $this->assign('current','search');
    }

    public function index($page = 1){


        $map = I('get.');


        if(IS_POST){
            $map = I('post.');
            redirect(U('Home/Search/index',$map));
        }
        $this->assign('map',$map);
        if(!empty($map['meet'])){
          $map['meet'] = ['like',"%{$map['meet']}%"];
        }

		if(!empty($map['sTime']) && !empty($map['eTime'])){
			$map['create_time'] = array('between',strtotime($map['sTime']).','.(strtotime($map['eTime'])+ 3600 * 24));
			unset($map['sTime']);
		}else{
            if(!empty($map['sTime']) && !empty($map['eTime']) ){
                $map['create_time'] = array('gt',strtotime($map['sTime']));
                unset($map['sTime']);
           }

            if (!empty($map['eTime'])) {
                $map['create_time'] = array('lt', strtotime($map['eTime']) + 3600 * 24);
                unset($map['eTime']);
            }

        }
		
		if(!empty($map['author'])){
			$map['author'] = array('like',"%{$map['author']}%");
		}
		
		if(!empty($map['ycode'])){
			$map['ycode'] = array('like',"%{$map['ycode']}%");
            $map['code'] = ['like',"%{$map['ycode']}%"];
		}
		
		if(!empty($map['title'])){
			$map['title'] = array('like',"%{$map['title']}%");
		}


		$mu = D('User/User');
		$mu->setModel(WEIYUAN);
		$user = $mu->getUser(get_uid());
		$roler = $user['主任'];

		$jdllw_str = D('FieldSetting')->where(array('profile_group_id'=>13,'field_name'=>'街道联络委'))->getField('form_default_value');
		$jdllw_arr = explode('|',$jdllw_str);
		
		$zwh_str = D('FieldSetting')->where(array('profile_group_id'=>13,'field_name'=>'专委会'))->getField('form_default_value');
		$zwh_arr = explode('|',$zwh_str);
		if(in_array($roler,$jdllw_str)){
			$map['jdllw'] = $roler;
		}
		
		if(in_array($roler,$zwh_arr)){
			$map['zwh'] = $roler;
		}
		
		
		
		$map  = array_filter($map);

		$m = D('Proposal');
		$tree = D('ProposalType')->where(array('status' => 1))->select();
		$this->assign('tree', $tree);

            $proposals = $m->where($map)->order('create_time desc')->page($page,16)->select();

            $totalCount = $m->where($map)->count();

            foreach($proposals as &$v){
                $v['type'] = $this->getProposalType($v[type_id]);

                $map['proposal_id'] = $v['id'];
                $units = D('ProposalResult')->where($map)->getField('unit',true);
                $v['units'] = implode(',',$units);
            }


		$this->assign('totalPageCount', $totalCount);
		$this->assign('proposals',$proposals);

			
		

		$this->display();

		
	}

    /**
     * @param int $page
     * MR.Z <327778155@qq.com>
     * create: 2016/11/15
     */
	public function export_list(){
        $map = I('get.');
        $map  = array_filter($map);

        $m = D('Proposal');
        $tree = D('ProposalType')->where(array('status' => 1))->select();
        $this->assign('tree', $tree);

        $proposals = $m->where($map)->order('create_time desc')->select();

        $totalCount = $m->where($map)->count();

        foreach($proposals as &$v){
            $v['type'] = $this->getProposalType($v[type_id]);

            $map['proposal_id'] = $v['id'];
            $units = D('ProposalResult')->where($map)->getField('unit',true);
            $v['units'] = implode(',',$units);
        }

        $filename = date('Y-m-d H:i:s',time()).'.xls';




        $this->_getExcel($filename,$proposals);





    }


    private function _getExcel($filename,$data){
        import("Org.Util.PHPExcel");
        import("Org.Util.PHPExcel.Writer.Excel5");
        import("Org.Util.PHPExcel.IOFactory.php");
        $objReader = \PHPExcel_IOFactory::createReader ( 'Excel5' );

         $objPHPExcel = $objReader->load ("./Public/templates.xls" );

        $objActSheet = $objPHPExcel->getActiveSheet ();
        $objActSheet->setTitle('提案列表');



        $baserow = 5;
        $status_proposal = C('PROPOSAL_STATUS');
        foreach($data as $k=>$v){
            $row = $baserow + $k;
            $objActSheet->setCellValue('A'.$row,$v['type']['title']);
            $objActSheet->setCellValue('B'.$row,$v['code'] ? $v['code'] : $v['ycode']);
            $objActSheet->setCellValue('C'.$row,$v['title']);
            $objActSheet->setCellValue('D'.$row,$v['author']);
            $objActSheet->setCellValue('E'.$row,$v['telephone']);
            $objActSheet->setCellValue('F'.$row,$v['units']);
            $objActSheet->setCellValue('G'.$row,$status_proposal[$v['status']]);
            $objActSheet->setCellValue('H'.$row,$v['mark']);
            $objActSheet->getRowDimension($row)->setRowHeight(30);

        }
        //边框样式
        $styleArray = array(
            'borders' => array(
                'allborders' => array(
                    //'style' => PHPExcel_Style_Border::BORDER_THICK,//边框是粗的
                    'style' => 'thick',//组边框
                    'color' => array('argb' => 'FFFF0000'),
                ),
            ),
        );

        $objActSheet->getStyle('A4:G'.$row)->applyFromArray($styleArray);
        $filename = iconv("utf-8", "gb2312", $filename);
        //设置活动单指数到第一个表,所以Excel打开这是第一个表
        $objPHPExcel->setActiveSheetIndex(0);
        header('Content-Type: application/vnd.ms-excel');
        header("Content-Disposition: attachment;filename=\"$filename\"");
        header('Cache-Control: max-age=0');

        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output'); //文件通过浏览器下载
        exit;



    }

	/*
	 * 提案展示详情页
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/10/20
	 */
	public function detail($id){
	    $proposal = D('Proposal')->find($id);

        $map_pr['proposal_id'] = $proposal['id'];
        $proposal_result = D('ProposalResult')->where($map_pr)->select();

        $map_pj['proposal_id'] =  $proposal['id'];
        $proposal_joint = D('ProposalJoint')->where($map_pj)->select();

        $m = D('User/User');
        $m->setModel(WEIYUAN);
        $users = $m->getUsers([],['名称','专委会','界别','街道联络委']);
        $new_users = [];
        foreach($users as $v){
            $new_users[$v['uid']] = $v;
        }
        $users = $new_users;
        foreach($proposal_joint as &$v){
            $v['user'] = $users[$v['user_id']];
        }

        $back_url = I('server.HTTP_REFERER');
        $this->assign('back_url',$back_url);
        $this->assign('proposal',$proposal);
        $this->assign('proposal_result',$proposal_result);
        $this->assign('proposal_joint',$proposal_joint);
       $this->display();
    }

    /*
     * 查看办理
     * author: MR.Z <327778155@qq.com>
     * create: 2016/10/20
     */
    public function handreply($result_id){
        $proposal_result = D('ProposalResult')->find($result_id);
        $proposal = D('Proposal')->find($proposal_result['proposal_id']);
        $back_url = I('server.HTTP_REFERER');
        $this->assign('back_url',$back_url);
        $this->assign('proposal',$proposal);
        $this->assign('proposal_result',$proposal_result);
        $this->display();

    }
	
	
	/**
	 * 获取提案类型
	 * @param $type_id
	 * @return mixed
	 * autor:xjw129xjt
	 */
	private function getProposalType($type_id)
	{
		$type = D('ProposalType')->where('id=' . $type_id)->find();
		return $type;
	}
	

}
