<?php
// +----------------------------------------------------------------------
// | OneThink [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013 http://www.onethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: 麦当苗儿 <zuojiazi@vip.qq.com> <http://www.zjzit.cn>
// +----------------------------------------------------------------------

namespace Home\Controller;
use Common\Controller\BaseController;

/**
 * 前台公共控制器
 * 为防止多分组Controller名称冲突，公共Controller名称统一使用分组名称
 */
class SearchController extends BaseController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('current','search');
    }

    public function index($page = 1){
		$map = I('post.');

        if(!empty($map['meet'])){
          $map['meet'] = ['like',"%{$map['meet']}%"];
        }
		
		if(!empty($map['sTime']) && !empty($map['eTime'])){
			$map['create_time'] = array('between',strtotime($map['sTime']).','.(strtotime($map['eTime'])+ 3600 * 24));
			unset($map['sTime']);
		}else{
            if(!empty($map['sTime']) && !empty($map['eTime']) ){
                $map['create_time'] = array('gt',strtotime($map['sTime']));
                unset($map['sTime']);
           }

            if (!empty($map['eTime'])) {
                $map['create_time'] = array('lt', strtotime($map['eTime']) + 3600 * 24);
                unset($map['eTime']);
            }

        }
		
		if(!empty($map['author'])){
			$map['author'] = array('like',"%{$map['author']}%");
		}
		
		if(!empty($map['ycode'])){
			$map['ycode'] = array('like',"%{$map['ycode']}%");
		}
		
		if(!empty($map['title'])){
			$map['title'] = array('like',"%{$map['title']}%");
		}
		
		$mu = D('User/User');
		$mu->setModel(WEIYUAN);
		$user = $mu->getUser(get_uid());
		$roler = $user['主任'];

		$jdllw_str = D('FieldSetting')->where(array('profile_group_id'=>13,'field_name'=>'街道联络委'))->getField('form_default_value');
		$jdllw_arr = explode('|',$jdllw_str);
		
		$zwh_str = D('FieldSetting')->where(array('profile_group_id'=>13,'field_name'=>'专委会'))->getField('form_default_value');
		$zwh_arr = explode('|',$zwh_str);
		if(in_array($roler,$jdllw_str)){
			$map['jdllw'] = $roler;
		}
		
		if(in_array($roler,$zwh_arr)){
			$map['zwh'] = $roler;
		}
		
		
		
		$map  = array_filter($map);

		$m = D('Proposal');
		$tree = D('ProposalType')->where(array('status' => 1))->select();
		$this->assign('tree', $tree);
		if(IS_POST){
		$proposals = $m->where($map)->order('create_time desc')->page($page,16)->select();

		$totalCount = $m->where($map)->count();
		
		foreach($proposals as &$v){
			$v['type'] = $this->getProposalType($v[type_id]);

			$map['proposal_id'] = $v['id'];
			$units = D('ProposalResult')->where($map)->getField('unit',true);
			$v['units'] = implode(',',$units);
		}
		}

		$this->assign('totalPageCount', $totalCount);
		$this->assign('proposals',$proposals);
		$this->display();
			
		

		$this->display();

		
	}
	
	
	/**
	 * 获取提案类型
	 * @param $type_id
	 * @return mixed
	 * autor:xjw129xjt
	 */
	private function getProposalType($type_id)
	{
		$type = D('ProposalType')->where('id=' . $type_id)->find();
		return $type;
	}
	

}
