<?php
// +----------------------------------------------------------------------
// | OneThink [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013 http://www.onethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: 麦当苗儿 <zuojiazi@vip.qq.com> <http://www.zjzit.cn>
// +----------------------------------------------------------------------

namespace Home\Controller;
use Common\Controller\BaseController;

/**
 * 前台公共控制器
 * 为防止多分组Controller名称冲突，公共Controller名称统一使用分组名称
 */
class StatisticsController extends BaseController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('current','statistics');
    }

    public function index(){


		$this->display();
	}
	
	/*
	 * 单个委员量化信息
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function weiyuan(){

        //获取会议次数列表
        $meets = M('ConfigMeet')->where('status=1')->order('id desc')->select();
        $this->assign('meets',$meets);
        $map = I('get.');

        if(IS_POST){
            $map = I('post.');
            //不得已而为之 ，TP3 不支持GET方法提交参数
            redirect(U('Home/Statistics/weiyuan',$map));
        }
        $this->assign('map',$map);
		$user_id = get_uid();
        $time = explode('~',C('STOCKTAK_DATE'));
        if($map['meet']){
            $configmeet =  M('ConfigMeet')->where("meet='{$map['meet']}'")->find();

            $year = ['stime'=>$configmeet['start_time'],'etime'=>$configmeet['end_time']];
        }

       $year = $map['meet'] ?  $year : ['stime'=>strtotime($time[0]),'etime'=>strtotime($time[1])];
		

		$m = D('User/User');
		$m->setModel(WEIYUAN);
		$member = $m->getUser($user_id);
		$this->getStatisticsResult($member['proposal'],$user_id,$year);


        //查找三个需要盘点的信息
        $map_st['create_time'] = ['between',$year['stime'].','.$year['etime']];
        $map_st['uid'] = $user_id;

        $stocktak_data = D('StocktakMeet')->where($map_st)->getField('id,uid,type,mark,score,create_time');

        $stock_tmp = [];
        foreach($stocktak_data as $v){
            $stock_tmp[$v['uid']][$v['type']]['mark'] = $v['mark'];
            $stock_tmp[$v['uid']][$v['type']]['score'] = $v['score'];
        }


            $member['qh'] = ($stock_tmp[$user_id]['qh']['mark'] && $stock_tmp[$user_id]['qh']['score']) ? $stock_tmp[$user_id]['qh']['mark'].'/'.$stock_tmp[$user_id]['qh']['score'] : '';
            $member['qzx'] = ($stock_tmp[$user_id]['qzx']['mark'] && $stock_tmp[$user_id]['qzx']['score']) ? $stock_tmp[$user_id]['qzx']['mark'].'/'.$stock_tmp[$user_id]['qzx']['score'] : '';
            $member['zwhjdllw'] = ($stock_tmp[$user_id]['zwhjdllw']['mark'] && $stock_tmp[$user_id]['zwhjdllw']['score']) ? $stock_tmp[$user_id]['zwhjdllw']['mark'].'/'.$stock_tmp[$v['uid']]['zwhjdllw']['score']:'';



		//出席区全体委员会议
		

		$this->assign('member',$member);
		$this->display();
	}
	
	/*
	 * 获取需要展示的委员量化统计的字段
	 *
	 *
	 */
	private function getStatisticsResult(&$arr=array(),$user_id,$year){
	
		$action_arr = array(17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43);
		foreach($action_arr as $v){
			$arr['action'.$v] = $this->getActionResult($v,$user_id,$year);
			
		}
		
	}
	/*
	 * 委员量化统计   政协办公室权限
	 * author:MR.Z <327778155@qq.com>
	 *  create: 2016/9/9
	 *  TODO 当前起始时间暂时不起作用
	 */
	public function weiyuans($page = 1){

	    //获取会议次数列表
        $meets = M('ConfigMeet')->where('status=1')->order('id desc')->select();
        $this->assign('meets',$meets);

		$m = D('User/User');
		$m->setModel(WEIYUAN);
		$proposal_weiyuan = $m->getUsers(array(),array('名称','手机号','专委会','街道联络委'));
        $map = I('get.');
		$pagesize = 16;
        if(IS_POST){
            $map = I('post.');


            //不得已而为之 ，TP3 不支持GET方法提交参数
            redirect(U('Home/Statistics/weiyuans',$map));
        }
        $this->assign('map',$map);
            $data = page_array($pagesize,$page,$proposal_weiyuan);
            $totalCount = count($proposal_weiyuan);

        $time = explode('~',C('STOCKTAK_DATE'));
        if($map['meet']){
            $configmeet =  M('ConfigMeet')->where("meet='{$map['meet']}'")->find();

            $year = ['stime'=>$configmeet['start_time'],'etime'=>$configmeet['end_time']];
        }

        $year = $map['meet'] ?  $year : ['stime'=>strtotime($time[0]),'etime'=>strtotime($time[1])];


            $map_st['create_time'] = ['between',$year['stime'].','.$year['etime']];

            $stocktak_data = D('StocktakMeet')->where($map_st)->getField('id,uid,type,mark,score,create_time');

            $stock_tmp = [];
            foreach($stocktak_data as $v){
                $stock_tmp[$v['uid']][$v['type']]['mark'] = $v['mark'];
                $stock_tmp[$v['uid']][$v['type']]['score'] = $v['score'];
            }


            foreach($data as $k=>$v){

                $this->getStatisticsResult($data[$k]['proposal'],$v['uid'],$year);

                    $data[$k]['qh'] = ($stock_tmp[$v['uid']]['qh']['mark'] && $stock_tmp[$v['uid']]['qh']['score']) ? $stock_tmp[$v['uid']]['qh']['mark'].'/'.$stock_tmp[$v['uid']]['qh']['score'] : '';
                    $data[$k]['qzx'] = ($stock_tmp[$v['uid']]['qzx']['mark'] && $stock_tmp[$v['uid']]['qzx']['score']) ? $stock_tmp[$v['uid']]['qzx']['mark'].'/'.$stock_tmp[$v['uid']]['qzx']['score'] : '';
                    $data[$k]['zwhjdllw'] = ($stock_tmp[$v['uid']]['zwhjdllw']['mark'] && $stock_tmp[$v['uid']]['zwhjdllw']['score']) ? $stock_tmp[$v['uid']]['zwhjdllw']['mark'].'/'.$stock_tmp[$v['uid']]['zwhjdllw']['score']:'';


            }


            $this->assign('totalPageCount', $totalCount);
            $this->assign('data',$data);


		$this->display();
	}
	
	
	/*
	 * 获取年度内量化信息结果
	 *
	 */
	private function getActionResult($action_id,$user_id,$year){

        $stime = $year['stime'];
        $etime = $year['etime'] ?  $year['etime'] + 3600 * 24 : 0;

        if($stime && $etime){
            $map['create_time'] = array('BETWEEN',$stime.','.$etime);
        }else{
            if($year['stime']){
                $map['create_time'] = ['gt',$stime];
            }elseif($year['etime']){
                $map['create_time'] = ['lt',$etime];
            }
        }
        $map['user_id'] = $user_id;
        $map['action_id'] = $action_id;

		$count = D('ActionLog')->where($map)->count();

		$rule = parse_action($action_id,$user_id);
		$rule = reset($rule);
		preg_match('/([\d]+)/',$rule['rule'],$match);
		$score = reset($match);

		if($rule['max'] < $count){
			$total_score = $score * $rule['max'] ;
			
		}else{
			$total_score = $score * $count;
		}
	
		$total_score = $total_score ? $total_score:0;
		$data['count'] = $count;
		$data['total_score'] = $total_score;
		return  $data;
		
	}
	
	
	

	
	/*
	 * 按委员或集体统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function byMember(){
		$page = I('get.page') ? I('get.page') : 1;
		$m = D('User/User');
		$m->setModel(WEIYUAN);
		$proposal_weiyuan = $m->getUsers(array(),array('名称'));
		$m->setModel(TEAM);
		$proposal_team = $m->getUsers(array(),array('名称'));
		$proposal_weiyuan = array_merge_recursive($proposal_weiyuan,$proposal_team);

		foreach($proposal_weiyuan as &$v){
			$v['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where uid={$v['uid']}"));
			
		}
		//print_r($proposal_weiyuan);
		
		$totalCount = count($proposal_weiyuan);
		
		$pagesize = 16;
		$data = page_array($pagesize,$page,$proposal_weiyuan);
		$this->assign('totalPageCount', $totalCount);
		$this->assign('statistics',$data);
		$this->display();
	}
	
	
	/*
 * 按提案类别统计
 * author: MR.Z <327778155@qq.com>
 * create: 2016/9/9
 */
	public function byType(){
		$types = D('ProposalType')->where('status=1')->select();
		foreach($types as &$v){
			$v['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where type_id={$v['id']}"));
	
		}
		
		$this->assign('statistics',$types);
		$this->display();
	}
	
	
	/*
	 * 按提案统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byProposal(){
		$data = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where status not in (0,1)"));

		$this->assign('data',$data);
		$this->display();
	}
	
	
	/*
 * 按提案满意数统计
 * author: MR.Z <327778155@qq.com>
 * create: 2016/9/9
 *
 */
	public function  bySatisfy(){
		$data = reset(M()->query("select sum(case when comment = 1 then 1 else 0 end) as comment1,
												sum(case when comment = 2 then 1 else 0 end) as comment2,
												sum(case when comment = 3 then 1 else 0 end) as comment3
												 from __PROPOSAL_RESULT__ 
												"));

		$this->assign('data',$data);
		
		
		$this->display();
	}
	
	
	/*
	 * 按办理单位数统计
	 *  author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function byUnitNumber(){
		$m = D('User/User');
		$m->setModel(UNIT);
		$members = $m->getUsers(array(),array('名称'));
		$newmembers = array();
		foreach($members as $v){
			$newmembers[$v[uid]] = $v;
		}
		

		$data = D('ProposalResult')->where(array('status'=>2))->group('user_id')->getField('user_id,count(user_id)');

		
		foreach($newmembers as $k=>$member){
			$newmembers[$k]['docount'] = $data[$k];
		}
		
		
	/*	foreach($data as $k=>$da){
			if(isset($newmembers[$k])){
				
				$data[$k] = $newmembers[$k];
				$data[$k]['docount'] = $da;
			}
		}
		*/
		$this->assign('data',$newmembers);
		$this->display();
	}
	
	/*
	 * 按专委会统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function byZwh(){

		$zwhstr = D('FieldSetting')->where(array('field_name'=>'专委会','profile_group_id'=>WEIYUAN))->getField('form_default_value');
		$zwharr = explode('|',$zwhstr);
		$data = array();
		foreach($zwharr as $k=>$z){
			$data[$k]['name'] = $z;
			$data[$k]['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where zwh='{$z}'"));

		}
	
		$this->assign('data',$data);
		$this->display();
	}
	
	/*
	 * 按界别组统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byJiebie(){
		$jiebiestr = D('FieldSetting')->where(array('field_name'=>'界别','profile_group_id'=>WEIYUAN))->getField('form_default_value');
		$jiebiearr = explode('|',$jiebiestr);
		$data = array();
		foreach($jiebiearr as $k=>$j){
			$data[$k]['name'] = $j;
			$data[$k]['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where jiebie='{$j}'"));
			
		}
		
		$this->assign('data',$data);
		
		
		$this->display();
	}
	

	
	/*
	 * 按街道联络统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byJdllw(){
		$jdllwstr = D('FieldSetting')->where(array('field_name'=>'街道联络委','profile_group_id'=>WEIYUAN))->getField('form_default_value');
		$jdllwarr = explode('|',$jdllwstr);
		$data = array();
		foreach($jdllwarr as $k=>$j){
			$data[$k]['name'] = $j;
			$data[$k]['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where jdllw='{$j}'"));
			
		}
		$this->assign('data',$data);
		$this->display();
	}
	
	
	
	/*
	 * 按办理结果统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byResult(){
		$data = reset(M()->query("select sum(case when rate like 'A%' then 1 else 0 end) as rateA,
												sum(case when rate like 'B%' then 1 else 0 end) as rateB,
												sum(case when rate like 'C%'  then 1 else 0 end) as rateC
												 from __PROPOSAL_RESULT__ 
												"));

		$this->assign('data',$data);
		
		

		$this->display();
	}



	

	
	

}
