<?php
// +----------------------------------------------------------------------
// | OneThink [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013 http://www.onethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: 麦当苗儿 <zuojiazi@vip.qq.com> <http://www.zjzit.cn>
// +----------------------------------------------------------------------

namespace Home\Controller;
use Common\Controller\BaseController;

/**
 * 前台公共控制器
 * 为防止多分组Controller名称冲突，公共Controller名称统一使用分组名称
 */
class StatisticsController extends BaseController {
    private $default_meet_id;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $default_meet = C('PROPOSAL_MEET');
        $this->default_meet_id = M('ConfigMeet')->where(['meet'=>$default_meet])->getField('id');
        $this->assign('current','statistics');
    }

    public function index(){
        //获取会议次数列表
        $meets = M('ConfigMeet')->where('status=1')->order('id desc')->select();
        $map = I('get.');
        $this->assign('map',$map);
        $this->assign('meets',$meets);

		$this->display();
	}
	
	/*
	 * 单个委员量化信息
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function weiyuan(){

        //获取会议次数列表
        $meets = M('ConfigMeet')->where('status=1')->order('id desc')->select();
        $this->assign('meets',$meets);
        $map = I('get.');

        if(IS_POST){
            $map = I('post.');
            //不得已而为之 ，TP3 不支持GET方法提交参数
            redirect(U('Home/Statistics/weiyuan',$map));
        }
        $this->assign('map',$map);
		$user_id = get_uid();
        $time = explode('~',C('STOCKTAK_DATE'));
        if($map['meet']){
            $configmeet =  M('ConfigMeet')->where("meet='{$map['meet']}'")->find();

            $year = ['stime'=>$configmeet['start_time'],'etime'=>$configmeet['end_time']];
        }

       $year = $map['meet'] ?  $year : ['stime'=>strtotime($time[0]),'etime'=>strtotime($time[1])];
		

		$m = D('User/User');
		$m->setModel(WEIYUAN);
		$member = $m->getUser($user_id);
		$this->getStatisticsResult($member['proposal'],$user_id,$year);


        //查找三个需要盘点的信息
        $map_st['create_time'] = ['between',$year['stime'].','.$year['etime']];
        $map_st['uid'] = $user_id;

        $stocktak_data = D('StocktakMeet')->where($map_st)->getField('id,uid,type,mark,score,create_time');

        $stock_tmp = [];
        foreach($stocktak_data as $v){
            $stock_tmp[$v['uid']][$v['type']]['mark'] = $v['mark'];
            $stock_tmp[$v['uid']][$v['type']]['score'] = $v['score'];
        }


            $member['qh'] = ($stock_tmp[$user_id]['qh']['mark'] && $stock_tmp[$user_id]['qh']['score']) ? $stock_tmp[$user_id]['qh']['mark'].'/'.$stock_tmp[$user_id]['qh']['score'] : '';
            $member['qzx'] = ($stock_tmp[$user_id]['qzx']['mark'] && $stock_tmp[$user_id]['qzx']['score']) ? $stock_tmp[$user_id]['qzx']['mark'].'/'.$stock_tmp[$user_id]['qzx']['score'] : '';
            $member['zwhjdllw'] = ($stock_tmp[$user_id]['zwhjdllw']['mark'] && $stock_tmp[$user_id]['zwhjdllw']['score']) ? $stock_tmp[$user_id]['zwhjdllw']['mark'].'/'.$stock_tmp[$v['uid']]['zwhjdllw']['score']:'';



		//出席区全体委员会议
		

		$this->assign('member',$member);
		$this->display();
	}
	
	/*
	 * 获取需要展示的委员量化统计的字段
	 *
	 *
	 */
	private function getStatisticsResult(&$arr=array(),$user_id,$year){
	
		$action_arr = array(17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43);
		foreach($action_arr as $v){
			$arr['action'.$v] = $this->getActionResult($v,$user_id,$year);
			
		}
		
	}
	/*
	 * 委员量化统计   政协办公室权限
	 * author:MR.Z <327778155@qq.com>
	 *  create: 2016/9/9
	 *  TODO 当前起始时间暂时不起作用
	 */
	public function weiyuans($page = 1){

	    //获取会议次数列表
        $meets = M('ConfigMeet')->where('status=1')->order('id desc')->select();
        $this->assign('meets',$meets);

		$m = D('User/User');
		$m->setModel(WEIYUAN);
		$proposal_weiyuan = $m->getUsers([],array('名称','手机号','专委会','街道联络委'));
        $map = I('get.');
		$pagesize = 16;
        if(IS_POST){
            $map = I('post.');


            //不得已而为之 ，TP3 不支持GET方法提交参数
            redirect(U('Home/Statistics/weiyuans',$map));
        }
        $this->assign('map',$map);
            $data = page_array($pagesize,$page,$proposal_weiyuan);
            $totalCount = count($proposal_weiyuan);

        $time = explode('~',C('STOCKTAK_DATE'));
        if($map['meet']){
            $configmeet =  M('ConfigMeet')->where("meet='{$map['meet']}'")->find();

            $year = ['stime'=>$configmeet['start_time'],'etime'=>$configmeet['end_time']];
        }

        $year = $map['meet'] ?  $year : ['stime'=>strtotime($time[0]),'etime'=>strtotime($time[1])];


            $map_st['create_time'] = ['between',$year['stime'].','.$year['etime']];

            $stocktak_data = D('StocktakMeet')->where($map_st)->getField('id,uid,type,mark,score,create_time');

            $stock_tmp = [];
            foreach($stocktak_data as $v){
                $stock_tmp[$v['uid']][$v['type']]['mark'] = $v['mark'];
                $stock_tmp[$v['uid']][$v['type']]['score'] = $v['score'];
            }


            foreach($data as $k=>$v){

                $this->getStatisticsResult($data[$k]['proposal'],$v['uid'],$year);

                    $data[$k]['qh'] = ($stock_tmp[$v['uid']]['qh']['mark'] && $stock_tmp[$v['uid']]['qh']['score']) ? $stock_tmp[$v['uid']]['qh']['mark'].'/'.$stock_tmp[$v['uid']]['qh']['score'] : '';
                    $data[$k]['qzx'] = ($stock_tmp[$v['uid']]['qzx']['mark'] && $stock_tmp[$v['uid']]['qzx']['score']) ? $stock_tmp[$v['uid']]['qzx']['mark'].'/'.$stock_tmp[$v['uid']]['qzx']['score'] : '';
                    $data[$k]['zwhjdllw'] = ($stock_tmp[$v['uid']]['zwhjdllw']['mark'] && $stock_tmp[$v['uid']]['zwhjdllw']['score']) ? $stock_tmp[$v['uid']]['zwhjdllw']['mark'].'/'.$stock_tmp[$v['uid']]['zwhjdllw']['score']:'';


            }


            $this->assign('totalPageCount', $totalCount);
            $this->assign('data',$data);
            if(I('get.action') == 'export'){
                $filename = date('Y-m-d H:i:s',time()).'.xls';
                $this->_explode_list($filename,$data);
            }

		$this->display();
	}


	private function _explode_list($filename,$data){
        $this->_getExcel($filename,$data);
    }

    private function _getExcel($filename,$data){
        import("Org.Util.PHPExcel");
        import("Org.Util.PHPExcel.Writer.Excel5");
        import("Org.Util.PHPExcel.IOFactory.php");
        $objReader = \PHPExcel_IOFactory::createReader ( 'Excel5' );

        $objPHPExcel = $objReader->load ("./Public/wylhtj.xls" );

        $objActSheet = $objPHPExcel->getActiveSheet ();
        $objActSheet->setTitle('委员量化统计');



        $baserow = 4;

        foreach($data as $k=>$member){
            $row = $baserow + $k;
            $objActSheet->setCellValue('A'.$row,$member['名称']);
            $objActSheet->setCellValue('B'.$row,$member['专委会'] );
            $objActSheet->setCellValue('C'.$row,$member['街道联络委']);
            $objActSheet->setCellValue('D'.$row,$member['score']);
            $objActSheet->setCellValue('E'.$row,$member['qh']);
            $objActSheet->setCellValue('F'.$row,$member['qzx']);
            $objActSheet->setCellValue('G'.$row,$member['zwhjdllws']);
            $objActSheet->setCellValue('H'.$row,$member['proposal']['action17']['total_score'] ? ($member['proposal']['action17']['count'].'/'.$member['proposal']['action17']['total_score']):'');
            $objActSheet->setCellValue('I'.$row,$member['proposal']['action20']['total_score'] ? ($member['proposal']['action20']['count'].'/'.$member['proposal']['action20']['total_score']) : '');
            $objActSheet->setCellValue('J'.$row,$member['proposal']['action21']['total_score'] ?($member['proposal']['action21']['count'].'/'.$member['proposal']['action21']['total_score']):'');
            $objActSheet->setCellValue('K'.$row,$member['proposal']['action22']['total_score'] ? ($member['proposal']['action22']['count'].'/'.$member['proposal']['action22']['total_score']) : '');
            $objActSheet->setCellValue('L'.$row,$member['proposal']['action23']['total_score'] ? ($member['proposal']['action23']['count'].'/'.$member['proposal']['action23']['total_score']) : '');
            $objActSheet->setCellValue('M'.$row,$member['proposal']['action24']['total_score'] ? ($member['proposal']['action24']['count'].'/'.$member['proposal']['action24']['total_score']) : '');
            $objActSheet->setCellValue('N'.$row,$member['proposal']['action25']['total_score'] ? ($member['proposal']['action25']['count'].'/'.$member['proposal']['action25']['total_score']) : '');
            $objActSheet->setCellValue('O'.$row,$member['proposal']['action42']['total_score'] ? ($member['proposal']['action42']['count'].'/'.$member['proposal']['action42']['total_score']) : '');
            $objActSheet->setCellValue('P'.$row,$member['proposal']['action26']['total_score'] ? ($member['proposal']['action26']['count'].'/'.$member['proposal']['action26']['total_score']) : '');
            $objActSheet->setCellValue('Q'.$row,$member['proposal']['action27']['total_score']? ($member['proposal']['action27']['count'].'/'.$member['proposal']['action27']['total_score']) : '');
            $objActSheet->setCellValue('R'.$row,$member['proposal']['action28']['total_score'] ? ($member['proposal']['action28']['count'].'/'.$member['proposal']['action28']['total_score']) : '');
            $objActSheet->setCellValue('S'.$row,$member['proposal']['action29']['total_score'] ? ($member['proposal']['action29']['count'].'/'.$member['proposal']['action29']['total_score']) : '');
            $objActSheet->setCellValue('T'.$row,$member['proposal']['action30']['total_score']? ($member['proposal']['action30']['count'].'/'.$member['proposal']['action30']['total_score']) : '');
            $objActSheet->setCellValue('U'.$row,$member['proposal']['action31']['total_score'] ? ($member['proposal']['action31']['count'].'/'.$member['proposal']['action31']['total_score']) : '');
            $objActSheet->setCellValue('V'.$row,$member['proposal']['action32']['total_score'] ? ($member['proposal']['action32']['count'].'/'.$member['proposal']['action32']['total_score']) : '');
            $objActSheet->setCellValue('W'.$row,$member['proposal']['action33']['total_score'] ? ($member['proposal']['action33']['count'].'/'.$member['proposal']['action33']['total_score']) : '');
            $objActSheet->setCellValue('X'.$row,$member['proposal']['action34']['total_score'] ? ($member['proposal']['action34']['count'].'/'.$member['proposal']['action34']['total_score']) : '');
            $objActSheet->setCellValue('Y'.$row,$member['proposal']['action35']['total_score'] ? ($member['proposal']['action35']['count'].'/'.$member['proposal']['action35']['total_score']) : '');
            $objActSheet->setCellValue('Z'.$row,$member['proposal']['action36']['total_score'] ? ($member['proposal']['action36']['count'].'/'.$member['proposal']['action36']['total_score']) : '');
            $objActSheet->setCellValue('AA'.$row,$member['proposal']['action37']['total_score'] ? ($member['proposal']['action37']['count'].'/'.$member['proposal']['action37']['total_score']) : '');
            $objActSheet->setCellValue('AB'.$row,$member['proposal']['action41']['total_score'] ? ($member['proposal']['action41']['count'].'/'.$member['proposal']['action41']['total_score']) : '');
            $objActSheet->setCellValue('AC'.$row,$member['proposal']['action38']['total_score'] ? ($member['proposal']['action38']['count'].'/'.$member['proposal']['action38']['total_score']) : '');
            $objActSheet->setCellValue('AD'.$row,$member['proposal']['action39']['total_score'] ? ($member['proposal']['action39']['count'].'/'.$member['proposal']['action39']['total_score']) : '');
            $objActSheet->setCellValue('AE'.$row,$member['proposal']['action40']['total_score'] ? ($member['proposal']['action40']['count'].'/'.$member['proposal']['action40']['total_score']) : '');


            $objActSheet->getRowDimension($row)->setRowHeight(30);

        }
        //边框样式
     /*   $styleArray = array(
            'borders' => array(
                'allborders' => array(
                    //'style' => PHPExcel_Style_Border::BORDER_THICK,//边框是粗的
                    'style' => 'thick',//组边框
                    'color' => array('argb' => 'FFFF0000'),
                ),
            ),
        );

        $objActSheet->getStyle('A4:G'.$row)->applyFromArray($styleArray);*/
        $filename = iconv("utf-8", "gb2312", $filename);
        //设置活动单指数到第一个表,所以Excel打开这是第一个表
        $objPHPExcel->setActiveSheetIndex(0);
        header('Content-Type: application/vnd.ms-excel');
        header("Content-Disposition: attachment;filename=\"$filename\"");
        header('Cache-Control: max-age=0');

        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output'); //文件通过浏览器下载
        exit;
    }

	/*
	 * 获取年度内量化信息结果
	 *
	 */
	private function getActionResult($action_id,$user_id,$year){

        $stime = $year['stime'];
        $etime = $year['etime'] ?  $year['etime'] + 3600 * 24 : 0;

        if($stime && $etime){
            $map['create_time'] = array('BETWEEN',$stime.','.$etime);
        }else{
            if($year['stime']){
                $map['create_time'] = ['gt',$stime];
            }elseif($year['etime']){
                $map['create_time'] = ['lt',$etime];
            }
        }
        $map['user_id'] = $user_id;
        $map['action_id'] = $action_id;

		$count = D('ActionLog')->where($map)->count();

		$rule = parse_action($action_id,$user_id);
		$rule = reset($rule);
		preg_match('/([\d]+)/',$rule['rule'],$match);
		$score = reset($match);

		if($rule['max'] < $count){
			$total_score = $score * $rule['max'] ;
			
		}else{
			$total_score = $score * $count;
		}
	
		$total_score = $total_score ? $total_score:0;
		$data['count'] = $count;
		$data['total_score'] = $total_score;
		return  $data;
		
	}
	
	
	

	
	/*
	 * 按委员或集体统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function byMember(){
		$page = I('get.page') ? I('get.page') : 1;
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$m = D('User/User');
		$m->setModel(WEIYUAN);
		$proposal_weiyuan = $m->getUsers(array(),array('名称'));
		$m->setModel(TEAM);
		$proposal_team = $m->getUsers(array(),array('名称'));
		$proposal_weiyuan = array_merge_recursive($proposal_weiyuan,$proposal_team);

		foreach($proposal_weiyuan as &$v){
			$v['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where uid={$v['uid']} and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));
			
		}

		//print_r($proposal_weiyuan);
		
		$totalCount = count($proposal_weiyuan);
		
		$pagesize = 16;
		$data = page_array($pagesize,$page,$proposal_weiyuan);
		$this->assign('totalPageCount', $totalCount);
		$this->assign('statistics',$data);
		$this->display();
	}
	
	
	/*
 * 按提案类别统计
 * author: MR.Z <327778155@qq.com>
 * create: 2016/9/9
 */
	public function byType(){

        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$types = D('ProposalType')->where('status=1')->select();
		foreach($types as &$v){
			$v['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where type_id={$v['id']} and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));
	
		}

		
		$this->assign('statistics',$types);
		$this->display();
	}
	
	
	/*
	 * 按提案统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byProposal(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$data = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where status not in (0,1) and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));

		$this->assign('data',$data);
		$this->display();
	}
	
	
	/*
 * 按提案满意数统计
 * author: MR.Z <327778155@qq.com>
 * create: 2016/9/9
 *
 */
	public function  bySatisfy(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$data = reset(M()->query("select sum(case when comment = 1 then 1 else 0 end) as comment1,
												sum(case when comment = 2 then 1 else 0 end) as comment2,
												sum(case when comment = 3 then 1 else 0 end) as comment3
												 from __PROPOSAL_RESULT__ 
												 and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));

		$this->assign('data',$data);
		
		
		$this->display();
	}
	
	
	/*
	 * 按办理单位数统计
	 *  author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function byUnitNumber(){
		$m = D('User/User');
		$m->setModel(UNIT);

        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$members = $m->getUsers(array(),array('名称'));
		$newmembers = array();
		foreach($members as $v){
			$newmembers[$v[uid]] = $v;
		}
		$map['create_time'] = ['between',$meet['start_time'].','.$meet['end_time']];
        $map['status'] = 2;

		$data = D('ProposalResult')->where($map)->group('user_id')->getField('user_id,count(user_id)');

		
		foreach($newmembers as $k=>$member){
			$newmembers[$k]['docount'] = $data[$k];
		}
		
		
	/*	foreach($data as $k=>$da){
			if(isset($newmembers[$k])){
				
				$data[$k] = $newmembers[$k];
				$data[$k]['docount'] = $da;
			}
		}
		*/
		$this->assign('data',$newmembers);
		$this->display();
	}
	
	/*
	 * 按专委会统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 *
	 */
	public function byZwh(){

        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$zwhstr = D('FieldSetting')->where(array('field_name'=>'专委会组','profile_group_id'=>WEIYUAN))->getField('form_default_value');
		$zwharr = array_filter(explode('|',$zwhstr));
		$data = array();
		foreach($zwharr as $k=>$z){
			$data[$k]['name'] = $z;
			$data[$k]['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where zwh='{$z}'  and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


		}
	
		$this->assign('data',$data);
		$this->display();
	}
	
	/*
	 * 按界别组统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byJiebie(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$jiebiestr = D('FieldSetting')->where(array('field_name'=>'界别','profile_group_id'=>WEIYUAN))->getField('form_default_value');
		$jiebiearr = array_filter(explode('|',$jiebiestr));
		$data = array();
		foreach($jiebiearr as $k=>$j){
			$data[$k]['name'] = $j;
			$data[$k]['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where jiebie='{$j}' and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));
			
		}
		
		$this->assign('data',$data);
		
		
		$this->display();
	}
	

	
	/*
	 * 按街道联络统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byJdllw(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

		$jdllwstr = D('FieldSetting')->where(array('field_name'=>'街道联络委','profile_group_id'=>WEIYUAN))->getField('form_default_value');
		$jdllwarr = array_filter(explode('|',$jdllwstr));
		$data = array();
		foreach($jdllwarr as $k=>$j){
			$data[$k]['name'] = $j;
			$data[$k]['count'] = reset(M()->query("select sum(case when recommend like '%1%' then 1 else 0 end) as countz,
												sum(case when recommend like '%2%' then 1 else 0 end) as countt,
												sum(case when recommend like  '%3%' then 1 else 0 end) as countj,
												sum(case when status not in (0,1,2,3,4,5,6,7) then 1 else 0 end) as countl,
												sum(case when status not in (0,1) then 1 else 0 end) as countta from __PROPOSAL__ 
												where jdllw='{$j}' and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));
			
		}
		$this->assign('data',$data);
		$this->display();
	}
	
	
	
	/*
	 * 按办理结果统计
	 * author: MR.Z <327778155@qq.com>
	 * create: 2016/9/9
	 */
	public function byResult(){

        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);
		$data = reset(M()->query("select sum(case when rate like 'A%' then 1 else 0 end) as rateA,
												sum(case when rate like 'B%' then 1 else 0 end) as rateB,
												sum(case when rate like 'C%'  then 1 else 0 end) as rateC
												 from __PROPOSAL_RESULT__ 
												 and create_time between '{$meet['start_time']}' and '{$meet['end_time']}'"));

		$this->assign('data',$data);
		
		

		$this->display();
	}


    public function bypolls_zwh(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

        $zwhstr = D('FieldSetting')->where(array('field_name'=>'专委会组','profile_group_id'=>WEIYUAN))->getField('form_default_value');
        $zwharr = array_filter(explode('|',$zwhstr));

        $data = array();
        foreach($zwharr as $k=>$z){
            $data[$k]['name'] = $z;
            $data[$k]['count'] = reset(M()->query("select sum(case when adopt like '%1%' then 1 else 0 end) as adopt_qzx,
												sum(case when adopt like '%2%' then 1 else 0 end) as adopt_szx,
												sum(case when adopt like '%3%'  then 1 else 0 end) as adopt_shzx,
												sum(case when adopt like '%4%'  then 1 else 0 end) as adopt_qgzx,
												sum(case when make like '%1%'  then 1 else 0 end) as make_qzx,
												sum(case when make like '%2%'  then 1 else 0 end) as make_szx,
												sum(case when make like '%3%'  then 1 else 0 end) as make_shzx,
												sum(case when make like '%4%'  then 1 else 0 end) as make_qgzx
												 from __POLLS__ 
												 where zwh='{$z}'   time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


        }






        $this->assign('data',$data);
        $this->display();
    }

    public function bypolls_jdllw(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

        $jdllwstr = D('FieldSetting')->where(array('field_name'=>'街道联络委','profile_group_id'=>WEIYUAN))->getField('form_default_value');
        $jdllwarr = array_filter(explode('|',$jdllwstr));

        $data = array();
        foreach($jdllwarr as $k=>$z){
            $data[$k]['name'] = $z;
            $data[$k]['count'] = reset(M()->query("select sum(case when adopt like '%1%' then 1 else 0 end) as adopt_qzx,
												sum(case when adopt like '%2%' then 1 else 0 end) as adopt_szx,
												sum(case when adopt like '%3%'  then 1 else 0 end) as adopt_shzx,
												sum(case when adopt like '%4%'  then 1 else 0 end) as adopt_qgzx,
												sum(case when make like '%1%'  then 1 else 0 end) as make_qzx,
												sum(case when make like '%2%'  then 1 else 0 end) as make_szx,
												sum(case when make like '%3%'  then 1 else 0 end) as make_shzx,
												sum(case when make like '%4%'  then 1 else 0 end) as make_qgzx
												 from __POLLS__ 
												 where jdllw='{$z}'   time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


        }






        $this->assign('data',$data);
        $this->display();
    }

    public function bypolls_jiebie(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

        $jiebiestr = D('FieldSetting')->where(array('field_name'=>'界别','profile_group_id'=>WEIYUAN))->getField('form_default_value');
        $jiebiearr = array_filter(explode('|',$jiebiestr));

        $data = array();
        foreach($jiebiearr as $k=>$z){
            $data[$k]['name'] = $z;
            $data[$k]['count'] = reset(M()->query("select sum(case when adopt like '%1%' then 1 else 0 end) as adopt_qzx,
												sum(case when adopt like '%2%' then 1 else 0 end) as adopt_szx,
												sum(case when adopt like '%3%'  then 1 else 0 end) as adopt_shzx,
												sum(case when adopt like '%4%'  then 1 else 0 end) as adopt_qgzx,
												sum(case when make like '%1%'  then 1 else 0 end) as make_qzx,
												sum(case when make like '%2%'  then 1 else 0 end) as make_szx,
												sum(case when make like '%3%'  then 1 else 0 end) as make_shzx,
												sum(case when make like '%4%'  then 1 else 0 end) as make_qgzx
												 from __POLLS__ 
												 where jiebie='{$z}'   time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


        }


        $this->assign('data',$data);
        $this->display();
    }

    public function byworking_zwh(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

        $zwhstr = D('FieldSetting')->where(array('field_name'=>'专委会组','profile_group_id'=>WEIYUAN))->getField('form_default_value');
        $zwharr = array_filter(explode('|',$zwhstr));

        $data = array();
        foreach($zwharr as $k=>$z){
            $data[$k]['name'] = $z;
            $data[$k]['count'] = reset(M()->query("select count(*)
												 from __POLLS__ 
												 where zwh='{$z}'   time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


        }






        $this->assign('data',$data);
        $this->display();
    }

    public function byworking_jdllw(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

        $jdllwstr = D('FieldSetting')->where(array('field_name'=>'街道联络委','profile_group_id'=>WEIYUAN))->getField('form_default_value');
        $jdllwarr = array_filter(explode('|',$jdllwstr));

        $data = array();
        foreach($jdllwarr as $k=>$z){
            $data[$k]['name'] = $z;
            $data[$k]['count'] = reset(M()->query("select count(*)
												 from __POLLS__ 
												 where jdllw='{$z}'   time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


        }






        $this->assign('data',$data);
        $this->display();
    }

    public function byworking_jiebie(){
        $meet_id = I('get.meet_id') ?  I('get.meet_id') : $this->default_meet_id;
        $meet = M('ConfigMeet')->find($meet_id);

        $jiebiestr = D('FieldSetting')->where(array('field_name'=>'界别','profile_group_id'=>WEIYUAN))->getField('form_default_value');
        $jiebiearr = array_filter(explode('|',$jiebiestr));

        $data = array();
        foreach($jiebiearr as $k=>$z){
            $data[$k]['name'] = $z;
            $data[$k]['count'] = reset(M()->query("select count(*)
												 from __POLLS__ 
												 where jiebie='{$z}'   time between '{$meet['start_time']}' and '{$meet['end_time']}'"));


        }


        $this->assign('data',$data);
        $this->display();
    }

	

	
	

}
